development:
  adapter: postgresql
  encoding: utf8
  database: pwdev
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: pwtest
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: pwprod
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST